# Header

menu:
  home: /
  laboratory: /lab/

# SubNav
subnav:
  github: "https://github.com/sookie2010"
  weibo: "https://weibo.com/2633013641"
  rss: "/atom.xml"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:colorfulsweet@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: https://i.loli.net/2018/05/04/5aeb37415a0dc.jpg

#是否开启分享
share_jia: true

#评论：1、畅言；2、Disqus；3、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/


#1、畅言
changyan_appid: false
changyan_conf: false

#2、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#3、gitalk
gitalk:
  enable: false
  ClientID: 90e8f648da2a669f7975
  ClientSecret: 7d2b602616387748ef0df10f7a8a626bdfd1034c
  repo: hexo_blog
  githubID: sookie2010
  adminUser: sookie2010
  distractionFreeMode: false

#4、Valine
valine:
  enable: true
  appId: 40jq6uO51rpVT4PEEcayYkda-gzGzoHsz
  appKey: nBOoOEDP4EBUfgpSJAF6idKi

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: all_articles
  friends: false #friends_link
  aboutme: about_me

friends: 
  友情链接1: http://localhost:6603/
  友情链接2: http://localhost:6603/
  友情链接3: http://localhost:6603/
  友情链接4: http://localhost:6603/
  友情链接5: http://localhost:6603/
  友情链接6: http://localhost:6603/

aboutme: 愿你最终能接纳每一面每一种的自己<br>独自活着便是团圆