# Header

menu:
  home: # 主页
    name: home
    url: / 
  archives: # 归档
    name: archives
    url: /archives/
    # target: _blank
  categories: # 分类
    name: categories
    url: /categories/
  photo_wall: # 照片墙
    name: photo_wall
    url: /photo_wall/

# SubNav
subnav:
  github: 
    url: https://github.com/sookie2010
    icon: github-alt
    alt: github_homepage
  weibo: 
    url: https://weibo.com/2633013641
    icon: weibo
    alt: weibo
  rss: 
    url: /atom.xml
    icon: rss
    alt: rss_subscription
  #zhihu: "#"
  #segmentfault: "#"
  mail: 
    url: mailto:colorfulsweet@gmail.com
    icon: mail
    alt: email
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: 谢谢你请我吃糖果
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: 目录，不存在的…

# 是否有快速回到顶部的按钮
top: true

# 站点图标
favicon: /favicon.ico

#头像url
avatar: https://cdn.colorfulsweet.site/resources/avatar.jpg

#是否开启分享
share_enable: true

#评论 Valine
valine:
  enable: true
  appId: 40jq6uO51rpVT4PEEcayYkda-gzGzoHsz
  appKey: nBOoOEDP4EBUfgpSJAF6idKi

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: all_articles
  friends: friends_link
  aboutme: about_me

friends: 
  十年饮冰，难凉热血: https://blog.colorfulsweet.site/
  †少女癌†: https://co5.me/
  猫与向日葵 : https://imjad.cn/
  coderfun: https://www.gxg.red/
  JENKINS: /jenkins/
  API管理后台: /admin/

aboutme: 愿你最终能接纳每一面每一种的自己<br>独自活着便是团圆