# 英语(默认)

categories: Categories
category: Category
search: Search
tags: Tags
tag: Tag
prev: Prev
next: Next
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
show_full_text: Show Full Text
home: Homepage
informal_essay: Informal Essay
photo_wall: Photo Wall
archives: Archives
all_articles: All Articles
friends_link: Friends Link
about_me: About Me
github_homepage: Github Homepage
weibo: Weibo
rss_subscription: Rss subscription
email: Email