#############################
# Xups for Hexo 主题配置文件
# Jelon
# http://jelon.top
#############################

#----------------------------
# 头部导航
#----------------------------
menu:
  home:
    name: 首页
    link: /
    icon: icon-home
  lab:
    name: 归档
    link: /archives/
    icon: icon-drawer
  about:
    name: 关于
    link: /about/
    icon: icon-user-tie
  rss:
    name: RSS
    link: /atom.xml
    icon: icon-rss

#----------------------------
# 副导航
#----------------------------
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"

#----------------------------
# RSS
#----------------------------
rss: /atom.xml
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

#----------------------------
# Favicon
#----------------------------
favicon: /favicon.ico

#----------------------------
# 头像url
#----------------------------
avatar: https://i.loli.net/2018/05/04/5aeb37415a0dc.jpg

#----------------------------
# 是否开启分享
#----------------------------
share: 
  enable: true
  list: 
    1: weibo
    2: qqzone
    3: qq
    4: douban

#----------------------------
# 是否开启评论
#----------------------------
comment:
  enable: true
  owner: sookie2010
  repo: hexo_blog
  client_id: 90e8f648da2a669f7975
  client_secret: 7d2b602616387748ef0df10f7a8a626bdfd1034c

#----------------------------
# 是否开启云标签
#----------------------------
tagcloud: 
  enable: true
  start_color: e87474
  end_color: 524ac5

#----------------------------
# 是否开启文章归档
#----------------------------
archives: 
  enable: true
  date_format: YYYY年MM月

#----------------------------
# 友情链接
#----------------------------
friends:
  enable: false
  list:
    1:
      name: google
      title: 谷歌
      link: https://www.google.com.hk/
    2:
      name: youtube
      title: 油管
      link: https://www.youtube.com/

#----------------------------
# 头部链接
#----------------------------
head_links:
  enable: true
  list:
    sup:
      0:
        name: Github
        link: https://github.com/sookie2010
      last:
        name: Hosted by Coding Pages
        link: https://pages.coding.me
    sub:
      sinaweibo:
        name: 新浪微博
        link: https://weibo.com/2633013641
      qqweibo:
        name: Facebook
        link: https://www.facebook.com/profile.php?id=100016469831631
#----------------------------
# SEO
#----------------------------
SEO:
  keywords: 前端, Web, Java
  description: 个人前端小站

#----------------------------
# 百度分析
#----------------------------
baidu_analytics: false

#----------------------------
# 高亮样式
#----------------------------
highlight_theme: night
#----------------------------
# CDN
# 如: //7xs305.com1.z0.glb.clouddn.com/
# 主要以下两个目录进行 cdn 存储
#   - img 图片资源下的 thumbnail 目录
#   - css 样式资源下的 fonts 目录
#----------------------------
CDN:
